version: '3.5'

services:

  mongo:
    container_name: mongo
    image: mongo:4-xenial
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - development

  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - development

networks:

  development:
    name: development
